#####   first run this on the anaconda propmt 
pip install fastf1

In [1]:
import fastf1
print(fastf1.__version__)

3.8.3

In [3]:
import pandas as pd
import fastf1
import os

CACHE_DIR = r"C:\Users\noela\OneDrive\Desktop\Machine Learning\fastf1 cache"

os.makedirs(CACHE_DIR, exist_ok=True)

fastf1.Cache.enable_cache(CACHE_DIR)

print("FastF1 cache enabled!")

FastF1 cache enabled!

In [4]:
session = fastf1.get_session(
    2025,
    "Las Vegas",
    "R"
)

In [5]:
session.load()

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api        WARNING 	Failed to align laps for drivers: ['5']
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
_api        WARNING 	Driver 11: Car data is incomplete!
_api        WARNING 	Driver 20: Car data is incomplete!
_api        WARNING 	Driver 24: Car data is incomplete!
_api        WARNING 	Driver 77: Car data is incomplete!
_api        WARNING 	Driver  5: Car data is incomplete!
_api        WARNING 	Driver  6: Car data is incomplete!
_api        WARNING 	Driver 12: Car data is incomplete!
_api        WARNING 	Driver 87: Car data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 11: Position data is incomplete!
_api        WARNING 	Driver 20: Position data is incomplete!
_api        WARNING 	Driver 24: Position data is incomplete!
_api        WARNING 	Driver 77: Position data is incomplete!
_api        WARNING 	Driver  5: Position data is incomplete!
_api        WARNING 	Driver  6: Position data is incomplete!
_api        WARNING 	Driver 12: Position data is incomplete!
_api        WARNING 	Driver 87: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '12', '16', '55', '6', '27', '44', '31', '87', '14', '22', '10', '30', '43', '23', '5', '18', '4', '81']

In [6]:
results = session.results

results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,1.0,1,2.0,NaT,NaT,NaT,0 days 01:21:08.429000,Finished,25.0,50.0
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,2.0,2,4.0,NaT,NaT,NaT,0 days 00:00:23.546000,Finished,18.0,50.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,3.0,3,17.0,NaT,NaT,NaT,0 days 00:00:30.488000,Finished,15.0,50.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,4,9.0,NaT,NaT,NaT,0 days 00:00:30.678000,Finished,12.0,50.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,5.0,5,3.0,NaT,NaT,NaT,0 days 00:00:34.924000,Finished,10.0,50.0

In [7]:
laps = session.laps

laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:59:23.959000,VER,1,0 days 00:01:42.062000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:32.691000,...,True,Red Bull Racing,0 days 00:57:41.627000,2025-11-23 04:04:08.478,12,1.0,False,,False,False
1,0 days 01:01:11.581000,VER,1,0 days 00:01:47.622000,2.0,1.0,NaT,NaT,0 days 00:00:28.482000,0 days 00:00:32.633000,...,True,Red Bull Racing,0 days 00:59:23.959000,2025-11-23 04:05:50.810,216,1.0,False,,False,False
2,0 days 01:03:25.115000,VER,1,0 days 00:02:13.534000,3.0,1.0,NaT,NaT,0 days 00:00:37.904000,0 days 00:00:44.898000,...,True,Red Bull Racing,0 days 01:01:11.581000,2025-11-23 04:07:38.432,6,1.0,False,,False,False
3,0 days 01:05:06.786000,VER,1,0 days 00:01:41.671000,4.0,1.0,NaT,NaT,0 days 00:00:31.896000,0 days 00:00:32.621000,...,True,Red Bull Racing,0 days 01:03:25.115000,2025-11-23 04:09:51.966,671,1.0,False,,False,False
4,0 days 01:06:44.207000,VER,1,0 days 00:01:37.421000,5.0,1.0,NaT,NaT,0 days 00:00:28.002000,0 days 00:00:32.386000,...,True,Red Bull Racing,0 days 01:05:06.786000,2025-11-23 04:11:33.637,1,1.0,False,,False,True

In [12]:
hamilton = laps.pick_drivers("HAM")

hamilton.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
350,0 days 00:59:32.021000,HAM,44,0 days 00:01:50.124000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:33.901000,...,True,Ferrari,0 days 00:57:41.627000,2025-11-23 04:04:08.478,12,13.0,False,,False,False
351,0 days 01:01:30.597000,HAM,44,0 days 00:01:58.576000,2.0,1.0,NaT,NaT,0 days 00:00:30.184000,0 days 00:00:34.510000,...,True,Ferrari,0 days 00:59:32.021000,2025-11-23 04:05:58.872,126,12.0,False,,False,False
352,0 days 01:03:39.778000,HAM,44,0 days 00:02:09.181000,3.0,1.0,NaT,NaT,0 days 00:00:38.263000,0 days 00:00:42.206000,...,True,Ferrari,0 days 01:01:30.597000,2025-11-23 04:07:57.448,671,12.0,False,,False,False
353,0 days 01:05:20.304000,HAM,44,0 days 00:01:40.526000,4.0,1.0,NaT,NaT,0 days 00:00:29.211000,0 days 00:00:33.076000,...,True,Ferrari,0 days 01:03:39.778000,2025-11-23 04:10:06.629,1,12.0,False,,False,True
354,0 days 01:06:57.972000,HAM,44,0 days 00:01:37.668000,5.0,1.0,NaT,NaT,0 days 00:00:28.326000,0 days 00:00:32.654000,...,True,Ferrari,0 days 01:05:20.304000,2025-11-23 04:11:47.155,1,12.0,False,,False,True

In [13]:
fastest = hamilton.pick_fastest()

fastest

Time                      0 days 02:18:14.995000
Driver                                       HAM
DriverNumber                                  44
LapTime                   0 days 00:01:34.553000
LapNumber                                   49.0
Stint                                        2.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:26.937000
Sector2Time               0 days 00:00:31.447000
Sector3Time               0 days 00:00:36.169000
Sector1SessionTime        0 days 02:17:07.391000
Sector2SessionTime        0 days 02:17:38.838000
Sector3SessionTime        0 days 02:18:15.007000
SpeedI1                                    183.0
SpeedI2                                      NaN
SpeedFL                                    323.0
SpeedST                                    329.0
IsPersonalBest                              True
Compound                                  MEDIUM
TyreLife                                    20.0
FreshTyre                                   True
Team                                     Ferrari
LapStartTime              0 days 02:16:40.442000
LapStartDate          2025-11-23 05:23:07.293000
TrackStatus                                    1
Position                                    10.0
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                  True
Name: 398, dtype: object

In [14]:
telemetry = fastest.get_car_data()

telemetry.head()

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2025-11-23 05:23:07.486,11604.0,325.0,8,99.0,False,0,car,0 days 00:00:00.193000,0 days 02:16:40.635000
1,2025-11-23 05:23:07.726,11616.0,327.0,8,98.0,False,0,car,0 days 00:00:00.433000,0 days 02:16:40.875000
2,2025-11-23 05:23:07.886,11636.0,327.0,8,98.0,False,0,car,0 days 00:00:00.593000,0 days 02:16:41.035000
3,2025-11-23 05:23:08.126,11628.0,326.0,8,98.0,False,0,car,0 days 00:00:00.833000,0 days 02:16:41.275000
4,2025-11-23 05:23:08.806,11533.0,325.0,8,98.0,False,0,car,0 days 00:00:01.513000,0 days 02:16:41.955000

In [23]:
lap_data = laps[
    [
        "Driver",
        "LapNumber",
        "LapTime",
        "Compound",
        "TyreLife",
        "FreshTyre",
        "Position"
    ]
]

In [24]:
lap_data.head()

,Driver,LapNumber,LapTime,Compound,TyreLife,FreshTyre,Position
0,VER,1.0,0 days 00:01:42.062000,MEDIUM,1.0,True,1.0
1,VER,2.0,0 days 00:01:47.622000,MEDIUM,2.0,True,1.0
2,VER,3.0,0 days 00:02:13.534000,MEDIUM,3.0,True,1.0
3,VER,4.0,0 days 00:01:41.671000,MEDIUM,4.0,True,1.0
4,VER,5.0,0 days 00:01:37.421000,MEDIUM,5.0,True,1.0

In [17]:
lap_data.isnull().sum()

Driver       0
LapNumber    0
LapTime      2
Compound     0
TyreLife     0
FreshTyre    0
Position     1
dtype: int64

In [19]:
lap_data = lap_data.dropna()

In [20]:
lap_data.isnull().sum()

Driver       0
LapNumber    0
LapTime      0
Compound     0
TyreLife     0
FreshTyre    0
Position     0
dtype: int64

In [25]:
lap_data["LapTime"] = lap_data["LapTime"].dt.total_seconds()

C:\Users\noela\AppData\Local\Temp\ipykernel_20448\1335652592.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lap_data["LapTime"] = lap_data["LapTime"].dt.total_seconds()

In [26]:
lap_data.head()

  Driver  LapNumber  LapTime Compound  TyreLife  FreshTyre  Position
0    VER        1.0  102.062   MEDIUM       1.0       True       1.0
1    VER        2.0  107.622   MEDIUM       2.0       True       1.0
2    VER        3.0  133.534   MEDIUM       3.0       True       1.0
3    VER        4.0  101.671   MEDIUM       4.0       True       1.0
4    VER        5.0   97.421   MEDIUM       5.0       True       1.0

In [29]:
driver_average = (
    lap_data
    .groupby("Driver")["LapTime"]
    .mean()
)

In [30]:
driver_average

Driver
ALB    101.942886
ALO     99.074740
ANT     97.878340
BEA     98.779560
BOR    130.427000
COL     99.569143
GAS     99.202620
HAD     98.273720
HAM     98.555960
HUL     98.391260
LAW     99.422857
LEC     97.982140
NOR     97.783400
OCO     98.581280
PIA     97.921580
RUS     97.839500
SAI     98.067060
STR           NaN
TSU     99.108060
VER     97.368580
Name: LapTime, dtype: float64

In [31]:
tyres = (
    lap_data
    .groupby(["Driver","Compound"])
    .size()
)

tyres

Driver  Compound
ALB     HARD        33
        MEDIUM       2
ALO     HARD        34
        MEDIUM      16
ANT     HARD        48
        SOFT         2
BEA     HARD        33
        MEDIUM      17
BOR     HARD         1
        MEDIUM       1
COL     HARD        25
        MEDIUM      24
GAS     HARD        48
        MEDIUM       2
HAD     HARD        30
        MEDIUM      20
HAM     HARD        29
        MEDIUM      21
HUL     HARD        30
        MEDIUM      20
LAW     HARD        47
        MEDIUM       2
LEC     HARD        26
        MEDIUM      24
NOR     HARD        28
        MEDIUM      22
OCO     HARD        23
        MEDIUM      27
PIA     HARD        29
        MEDIUM      21
RUS     HARD        33
        MEDIUM      17
SAI     HARD        28
        MEDIUM      22
STR     MEDIUM       1
TSU     HARD        26
        MEDIUM      24
VER     HARD        25
        MEDIUM      25
dtype: int64

In [33]:
lap_data.to_csv(
    "F1_lap_data.csv",
    index=False
)