In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
    'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
    'Sales': [200, 120, 340, 124, 243, 350]
}

In [4]:
df=pd.DataFrame(data)

In [5]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [10]:
bycomp=df.groupby('Company')
bycomp

In [12]:
bycomp['Sales'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [13]:
bycomp.sum()

             Person  Sales
Company
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [15]:
bycomp.sum().loc["FB"]

Person    CarlSarah
Sales           593
Name: FB, dtype: object

In [16]:
df.groupby("Company").sum().loc["FB"]

Person    CarlSarah
Sales           593
Name: FB, dtype: object

In [17]:
bycomp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [20]:
df.groupby("Company").describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0